### PR TITLE
chore: change spacing responsability to layout

### PR DESCRIPTION
**Pull request by leandrogrillo**
## Summary
It is a chore 💅🏻 

I would suggest to keep all the spacing to the layout components instead of adding then to the components :)

## Preview

image
image

### CODE REVIEW

**Comment by DanielHe4rt** [comment]
Seems good but we have some conflicts here. Can you check what happened?

**Comment by leandrogrillo** [comment]
@DanielHe4rt @voomsuetam done!

CleanShot 2024-08-08 at 12 18 26

**Review by voomsuetam — COMMENTED** [review]
LGTM!

**Comment by DanielHe4rt** [comment]
I'll merge it and fix this issue (probably I'll take an hour because I still suck at front-end LOLOL) but thanks in any case @leandrogrillo.

**Pull request merged**
